---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: redpencil/varnish-post
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
    - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: redpencil/varnish-post
    dry_run: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: redpencil/varnish-post
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: CHpHm+3Z3d53O9TbfS5GwHmvI7NTdgNt5e8dwSoZHNs=
---
kind: secret
name: docker_password
data: qT3M70ePCoL2R09c33HdbKYVF5wTqiEGo7xL3Ma4IDq7pTBrWq8TnPUgz5fe7Y8po6uMLNO7VKsiExc6fX8PsQ==
---
kind: signature
hmac: b11f52a9edfd8386f543c4fcca9a342e35a4c64fdc82ac75c6db0f6e8fb9d571

...
